spring.application.name=new-app
# logging.level.org.springframework.web.client.RestTemplate=DEBUG
# logging.level.org.apache.http=DEBUG


api.secret=57bbdbef590d9c3
api.cle=5406028b547eceb
api.baseUrl=http://localhost:8000

